[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = {workspace = true}
kernel = {workspace = true}

[dev-dependencies]
kernel = {workspace =  true, features = ["test-utils"]}
